#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

# List all services *except* PostgreSQL databases here
services:
  # A web service on the Python native runtime
  - type: web
    runtime: python
    name: tros-appointment-bp
    repo: https://github.com/Genius-Excel/appointment.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: master      # Default: master
    buildCommand: pip install -r requirements.txt
    preDeployCommand: gunicorn appointment.wsgi
    startCommand: gunicorn appointment.wsgi
    autoDeploy: false # Disable automatic deploys
    # maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    domains: # Custom domains
      - trostech.oregon.com
      - favour.oregon.com
    envVars: # Environment variables
      - key: REDIS_PASS
        value: m78Bgsa3JZkGT2qBk4l63rWXSDBrsint
  - type: worker
    runtime: python
    name: tros-appointment-celery-worker
    repo: https://github.com/Genius-Excel/appointment.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: master      # Default: master
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A appointment worker --loglevel=info
    
  # A worker service to run Celery Beat
  - type: worker
    runtime: python
    name: tros-appointment-celery-beat
    repo: https://github.com/Genius-Excel/appointment.git # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon # Default: oregon
    plan: free    # Default: starter
    branch: master      # Default: master
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A appointment beat --loglevel=info