# Generated by Django 4.1.5 on 2024-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('mobile_number', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=150, null=True)),
                ('selected_property', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.DateTimeField()),
            ],
        ),
    ]
