# Generated by Django 4.1.5 on 2024-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_clientappointment_selected_property_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CradenMooreClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=100)),
                ('meeting_link', models.CharField(max_length=250)),
            ],
        ),
    ]
