# Generated by Django 4.1.5 on 2024-08-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_cradenmooreclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnishBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('mobile_number', models.CharField(max_length=100)),
                ('restaurant_location', models.CharField(max_length=250)),
                ('number_of_guests', models.CharField(max_length=150)),
                ('appointment_date', models.CharField(max_length=150)),
            ],
        ),
    ]
