# Generated by Django 5.1 on 2024-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_enishbookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryClinicCustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('customer_query_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
