# Generated by Django 5.1 on 2024-10-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_laundrycliniccustomerquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laundrycliniccustomerquery',
            old_name='ai_response',
            new_name='ai_email_response',
        ),
    ]
