# Generated by Django 5.1 on 2024-10-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_rename_ai_response_laundrycliniccustomerquery_ai_email_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundrycliniccustomerquery',
            name='language_mode',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], default='English', max_length=50, null=True),
        ),
    ]
