# Generated by Django 5.1 on 2024-10-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_laundrycliniccustomerquery_language_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryClinicEnglishSpeakingCustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('customer_query_message', models.TextField()),
                ('customer_comments', models.TextField()),
                ('ai_assistant_response', models.TextField()),
                ('laundry_event_details', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField()),
                ('ai_email_response', models.TextField()),
                ('phone_number', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
