# Generated by Django 5.1 on 2024-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_alter_laundryclinicenglishspeakingcustomerquery_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryClinicSpanishSpeakingCustomerQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('customer_query_message_english', models.TextField(null=True)),
                ('customer_query_message_spanish', models.TextField(null=True)),
                ('customer_comments_english', models.TextField(null=True)),
                ('customer_comments_spanish', models.TextField(null=True)),
                ('ai_assistant_response_english', models.TextField(null=True)),
                ('ai_assistant_response_spanish', models.TextField(null=True)),
                ('laundry_event_details_english', models.TextField(null=True)),
                ('laundry_event_details_spanish', models.TextField(null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('timestamp', models.DateTimeField()),
                ('ai_email_response_spanish', models.TextField()),
            ],
        ),
    ]
