# Generated by Django 5.1 on 2024-10-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0010_laundryclinicspanishspeakingcustomerquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryclinicspanishspeakingcustomerquery',
            name='spreadsheet_row',
            field=models.IntegerField(null=True),
        ),
    ]
