# Generated by Django 5.1 on 2024-10-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0011_laundryclinicspanishspeakingcustomerquery_spreadsheet_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryclinicenglishspeakingcustomerquery',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laundryclinicenglishspeakingcustomerquery',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
