# Generated by Django 5.1 on 2024-10-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0012_alter_laundryclinicenglishspeakingcustomerquery_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laundryclinicspanishspeakingcustomerquery',
            name='ai_email_response_spanish',
            field=models.TextField(null=True),
        ),
    ]
