# Generated by Django 5.1 on 2024-10-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0015_ceracerni_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceracerni',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
