# Generated by Django 5.1 on 2024-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0016_alter_ceracerni_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryclinicenglishspeakingcustomerquery',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laundryclinicspanishspeakingcustomerquery',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=50, null=True),
        ),
    ]
