# Generated by Django 5.1 on 2024-11-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0018_ceracerni_booking_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryClinicVoiceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('call_summary', models.TextField()),
                ('call_transcript', models.TextField()),
                ('call_recordings', models.FileField(null=True, upload_to='laundry-clinic-ai-call-recordings/')),
            ],
        ),
    ]
