# Generated by Django 5.1 on 2024-12-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0021_rename_call_recordings_laundryclinicvoicecall_recording_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
